scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    metrics_path: '/metrics'
    basic_auth:
      username: 'guest'
      password: 'guest'

  - job_name: 'celery'
    static_configs:
      - targets: ['flower:5555']
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
